CREATE TABLE cadastro_vinhos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    pais VARCHAR(100) NOT NULL,
    adega VARCHAR(255) NOT NULL,
    safra INT NOT NULL CHECK (safra BETWEEN 1000 AND 9999),
    imagem VARCHAR(500),
    uva VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Ativo' CHECK (status IN ('Ativo', 'Inativo')),
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);